abbrev_map = {
    "r": "are",
    "u": "you",
    "cos": "because",
    "bcos": "because",
    "cus": "because",
    "cuz": "because",
    "bcuz": "because",
    "alot": "a lot",
    "fav": "favourite",
    "omg": "oh my god",
    "dont": "do not",
    "im": "i am",
    "yall": "you all",
    "luv": "love",
    "fav": "favourite",
    "lmao": "lol",
    "lmfao": "lol",
    "pls": "please",
    "ur": "your",
    "yt": "youtube",
    "wtf": "what the fuck",
    "plz": "please",
    "pls": "please",
    "idk": "i do not know",
    "idc": "i do not care",
    "idgaf": "i do not give a fuck",
    "bwl": "bursting with laughter",
    "ya": "yes",
    "yea": "yes",
    "ye": "yes",
    "yah": "yes",
    "k": "ok",
    "btw": "by the way",
    "ppl": "people",
    "fam": "family",
    "tbh": "to be honest",
    "ikr": "i know right",
    "dis": "this",
    "af": "as fuck",
    "cmon": "come on",
    "thx": "thanks",
    "omfg": "oh my fucking god",
    "stfu": "shut the fuck up",
    "wth": "what the hell",
    "abt": "about",
    "smh": "shaking my head",
    "ofc": "of course",
    "wat": "what",
    "wot": "what",
    "asap": "as soon as possible",
    "dafuq": "the fuck",
    "sry": "sorry",
    "rly": "really",
    "rlly": "really",
    "wut": "what",
    "mv": "music video",
    "arent": "are not",
    "couldnt": "could not",
    "didnt": "did not",
    "doesnt": "does not",
    "hadnt": "had not",
    "hasnt": "has not",
    "havent": "have not",
    "isnt": "is not",
    "mightnt": "might not",
    "mustnt": "must not",
    "neednt": "neet not",
    "shant": "shall not",
    "shouldnt": "should not",
    "wasnt": "was not",
    "werent": "were not",
    "wont": "will not",
    "wouldnt": "would not"
    }

    
